use movieapp2;
drop table actedin;
drop table bornin;
drop table countryabbrev;
drop table directed;
drop table dislikedmovie;
drop table distinctplacewithcoord;
drop table favoritemovie;
drop table favoriteperson;
drop table likedmovie;
drop table likedpeople;
drop table movie;
drop table person;
drop table place;
drop table programuser;